name: FCD-meld
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pytest=7.0.1
  - jupyterlab=3.2.9
  - h5py=3.6.0
  - fpdf=1.7.2
  - scikit-image=0.18
  - pip=23.3.1
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - torchmetrics==1.4.2
      - pytorch-lightning==2.4.0

  - torchvision
  - torchaudio
  - pip:
      - potpourri3d==0.0.6
      - captum==0.6.0
      - pandas==1.4.1
      - matplotlib==3.5.1
      - neuroCombat==0.2.12
      - nibabel==5.3.2         # совместим с NumPy 2.x
      - nilearn==0.10.2
      - patsy==0.5.4
      - progressbar2==4.2.0
      - statsmodels==0.14.1
      - seaborn==0.11.0
      - matplotlib_surface_plotting==0.10
      - numpy==1.22.0
      - pytest==6.2.3
      - torch-scatter -f https://data.pyg.org/whl/torch-2.5.1+cu121.html
      - torch-geometric==2.5.3
      - lapy==0.6.0            # для fastsurfer
      - SimpleITK==2.1.1       # для fastsurfer
      - pybids==0.16.4
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - transformers==4.44.2
      - monai==1.3.2
      - uvicorn
      - fastapi
